<#
.SYNOPSIS
    PEST++ Agent Deployment Script for Windows

.DESCRIPTION
    Deploys PEST++ agents to remote machines on your local network via SSH.
    Handles copying files, building Docker images, and starting containers.

.PARAMETER ConfigFile
    Path to the config file with machine list (default: agents.conf)

.PARAMETER ManagerIP
    IP address of the main server running the PEST++ manager

.PARAMETER NumAgents
    Default number of agents per machine (default: 4)

.PARAMETER Build
    Force rebuild of Docker image on remote machines

.PARAMETER Stop
    Stop agents on all machines instead of starting them

.EXAMPLE
    .\deploy-agents.ps1 -ManagerIP 192.168.1.100

.EXAMPLE
    .\deploy-agents.ps1 -ManagerIP 192.168.1.100 -NumAgents 6 -Build

.EXAMPLE
    .\deploy-agents.ps1 -ManagerIP 192.168.1.100 -Stop
#>

param(
    [string]$ConfigFile = "",
    [string]$ManagerIP = "",
    [int]$NumAgents = 4,
    [switch]$Build,
    [switch]$Stop,
    [switch]$Help
)

# Colors
$Colors = @{
    Info = "Cyan"
    Success = "Green"
    Warning = "Yellow"
    Error = "Red"
}

# Script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir
$RemoteDir = "/tmp/pest-agents"

# Files to deploy
$DeployFiles = @(
    "Dockerfile.pest-agent"
    "docker-compose.agent.yml"
    ".env.agent.example"
    "scripts/pest-agent-entrypoint.sh"
    "scripts/start-agents.sh"
)

function Write-Header {
    Write-Host ""
    Write-Host "==============================================" -ForegroundColor $Colors.Info
    Write-Host "  PEST++ Agent Deployment Script (PowerShell)" -ForegroundColor $Colors.Info
    Write-Host "==============================================" -ForegroundColor $Colors.Info
    Write-Host ""
}

function Write-Log {
    param(
        [string]$Message,
        [string]$Level = "Info"
    )

    $color = $Colors[$Level]
    $prefix = switch ($Level) {
        "Info" { "[INFO]" }
        "Success" { "[OK]" }
        "Warning" { "[WARN]" }
        "Error" { "[ERROR]" }
    }

    Write-Host "$prefix " -ForegroundColor $color -NoNewline
    Write-Host $Message
}

function Test-SSHConnection {
    param(
        [string]$Host,
        [string]$User
    )

    try {
        $result = ssh -o BatchMode=yes -o ConnectTimeout=5 "${User}@${Host}" "echo ok" 2>$null
        return $result -eq "ok"
    }
    catch {
        return $false
    }
}

function Deploy-ToMachine {
    param(
        [string]$HostAddress,
        [string]$User,
        [int]$AgentCount
    )

    Write-Host ""
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor $Colors.Info
    Write-Log "Deploying to ${User}@${HostAddress} (${AgentCount} agents)"
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor $Colors.Info

    # Check SSH connectivity
    Write-Log "Checking SSH connectivity..."
    if (-not (Test-SSHConnection -Host $HostAddress -User $User)) {
        Write-Log "Cannot connect to ${User}@${HostAddress}" -Level "Error"
        Write-Log "Make sure SSH key authentication is set up" -Level "Error"
        return $false
    }
    Write-Log "SSH connection OK" -Level "Success"

    # Check Docker on remote
    Write-Log "Checking Docker on remote machine..."
    $dockerCheck = ssh "${User}@${HostAddress}" "docker --version" 2>$null
    if (-not $dockerCheck) {
        Write-Log "Docker not found on ${HostAddress}" -Level "Error"
        return $false
    }
    Write-Log "Docker available" -Level "Success"

    # Create remote directory
    Write-Log "Creating remote directory..."
    ssh "${User}@${HostAddress}" "mkdir -p ${RemoteDir}/scripts"

    # Copy files
    Write-Log "Copying deployment files..."
    foreach ($file in $DeployFiles) {
        $src = Join-Path $ProjectDir $file
        $dest = "${RemoteDir}/${file}"

        if (Test-Path $src) {
            scp -q $src "${User}@${HostAddress}:${dest}"
            Write-Log "  Copied ${file}" -Level "Success"
        }
        else {
            Write-Log "  File not found: ${file}" -Level "Warning"
        }
    }

    # Create .env file
    Write-Log "Creating .env configuration..."
    $envContent = @"
# PEST++ Agent Configuration
# Auto-generated by deploy-agents.ps1

MANAGER_HOST=${ManagerIP}
MANAGER_PORT=4004
MINIO_HOST=${ManagerIP}
MINIO_PORT=9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
NUM_AGENTS=${AgentCount}
"@

    $envContent | ssh "${User}@${HostAddress}" "cat > ${RemoteDir}/.env"
    Write-Log ".env created" -Level "Success"

    # Make scripts executable
    ssh "${User}@${HostAddress}" "chmod +x ${RemoteDir}/scripts/*.sh 2>/dev/null || true"

    # Build Docker image if needed
    $imageExists = ssh "${User}@${HostAddress}" "docker images | grep -q modflow-pest-agent && echo yes"
    if ($Build -or ($imageExists -ne "yes")) {
        Write-Log "Building Docker image (this may take a few minutes)..."
        ssh "${User}@${HostAddress}" "cd ${RemoteDir} && docker build -f Dockerfile.pest-agent -t modflow-pest-agent:latest ."
        Write-Log "Docker image built" -Level "Success"
    }
    else {
        Write-Log "Docker image already exists (use -Build to force rebuild)"
    }

    # Stop existing agents
    Write-Log "Stopping any existing agents..."
    ssh "${User}@${HostAddress}" "docker ps -q --filter 'name=pest-agent-' | xargs -r docker stop 2>/dev/null || true"
    ssh "${User}@${HostAddress}" "docker ps -aq --filter 'name=pest-agent-' | xargs -r docker rm 2>/dev/null || true"

    if ($Stop) {
        Write-Log "Agents stopped on ${HostAddress}" -Level "Success"
        return $true
    }

    # Start agents
    Write-Log "Starting ${AgentCount} agents..."
    ssh "${User}@${HostAddress}" "cd ${RemoteDir} && docker compose -f docker-compose.agent.yml up -d --scale pest-agent=${AgentCount}"

    # Verify agents are running
    Start-Sleep -Seconds 2
    $running = ssh "${User}@${HostAddress}" "docker ps --filter 'name=pest-agent' --format '{{.Names}}' | wc -l"

    if ([int]$running -gt 0) {
        Write-Log "${running} agent(s) running on ${HostAddress}" -Level "Success"
    }
    else {
        Write-Log "No agents appear to be running on ${HostAddress}" -Level "Warning"
    }

    return $true
}

# =============================================================================
# Main
# =============================================================================

if ($Help) {
    Get-Help $MyInvocation.MyCommand.Path -Detailed
    exit 0
}

Write-Header

# Set config file path
if (-not $ConfigFile) {
    $ConfigFile = Join-Path $ScriptDir "agents.conf"
}

# Check for config file
if (-not (Test-Path $ConfigFile)) {
    Write-Log "Config file not found: ${ConfigFile}" -Level "Warning"
    Write-Log "Creating example config file..."

    $exampleConfig = @"
# PEST++ Agent Deployment Configuration
# Format: hostname_or_ip [username] [num_agents]
#
# Examples:
#   192.168.1.101 user 4
#   192.168.1.102 admin 6
#
# SSH key authentication must be set up first

# === Add your machines below ===
# 192.168.1.101 user 4
"@

    $exampleConfig | Out-File -FilePath $ConfigFile -Encoding UTF8
    Write-Log "Edit ${ConfigFile} and add your machines"
    exit 1
}

# Check for manager IP
if (-not $ManagerIP) {
    Write-Log "Manager IP not specified" -Level "Error"
    Write-Log "Use -ManagerIP to specify the main server IP"
    exit 1
}

Write-Log "Manager IP: ${ManagerIP}"
Write-Log "Config file: ${ConfigFile}"
Write-Log "Default agents per machine: ${NumAgents}"
Write-Host ""

# Parse config file and count machines
$machines = @()
Get-Content $ConfigFile | ForEach-Object {
    $line = $_.Trim()

    # Skip comments and empty lines
    if ($line -match "^#" -or $line -eq "") {
        return
    }

    $parts = $line -split '\s+'
    $machine = @{
        Host = $parts[0]
        User = if ($parts.Count -gt 1) { $parts[1] } else { $env:USERNAME }
        Agents = if ($parts.Count -gt 2) { [int]$parts[2] } else { $NumAgents }
    }
    $machines += $machine
}

if ($machines.Count -eq 0) {
    Write-Log "No machines found in config file" -Level "Error"
    Write-Log "Edit ${ConfigFile} and add your machines"
    exit 1
}

$totalAgents = ($machines | Measure-Object -Property Agents -Sum).Sum

Write-Log "Found $($machines.Count) machine(s) in config"
Write-Log "Total agents to deploy: ${totalAgents}"
Write-Host ""

$action = if ($Stop) { "Stop agents on" } else { "Deploy to" }
$confirm = Read-Host "${action} all $($machines.Count) machine(s)? (y/n)"
if ($confirm -notmatch "^[Yy]") {
    Write-Log "Aborted"
    exit 0
}

# Deploy to each machine
$successCount = 0
$failCount = 0

foreach ($machine in $machines) {
    $result = Deploy-ToMachine -HostAddress $machine.Host -User $machine.User -AgentCount $machine.Agents
    if ($result) {
        $successCount++
    }
    else {
        $failCount++
    }
}

# Summary
Write-Host ""
Write-Host "==============================================" -ForegroundColor $Colors.Info
Write-Host "  Deployment Summary" -ForegroundColor $Colors.Info
Write-Host "==============================================" -ForegroundColor $Colors.Info
Write-Host ""
Write-Log "Successful: ${successCount}"
if ($failCount -gt 0) {
    Write-Log "Failed: ${failCount}" -Level "Error"
}
Write-Host ""

if (-not $Stop) {
    Write-Log "To verify agents are running:"
    Write-Host "    ssh user@host 'docker ps --filter name=pest-agent'"
    Write-Host ""
    Write-Log "To view agent logs:"
    Write-Host "    ssh user@host 'docker logs -f pest-agent-1'"
    Write-Host ""
    Write-Log "To stop all agents:"
    Write-Host "    .\deploy-agents.ps1 -ManagerIP ${ManagerIP} -Stop"
}
